package lift.xql.community.mapper;

import java.util.List;
import lift.xql.community.model.Questions;
import lift.xql.community.model.QuestionsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    long countByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    int deleteByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    int insert(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    int insertSelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    List<Questions> selectByExampleWithBLOBsWithRowbounds(QuestionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    List<Questions> selectByExampleWithBLOBs(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    List<Questions> selectByExampleWithRowbounds(QuestionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    List<Questions> selectByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Mar 21 10:47:06 CST 2020
     */
    int updateByExample(@Param("record") Questions record, @Param("example") QuestionsExample example);
}